time:
	gcc t_time.h t_time.c

timetable:
	gcc t_time.h t_time.c t_timetable.h t_timetable.c

table:
	gcc t_time.h t_time.c t_timetable.h t_timetable.c table.h table.c

all:
	gcc t_time.h t_time.c t_timetable.h t_timetable.c table.h table.c main.c