time:
	gcc -Wall t_time.h t_time.c

timetable:
	gcc -Wall t_time.h t_time.c t_timetable.h t_timetable.c

table:
	gcc -Wall t_time.h t_time.c t_timetable.h t_timetable.c table.h table.c

all:
	gcc -Wall t_time.h t_time.c t_timetable.h t_timetable.c table.h table.c main.c

debug:
	gcc -g t_time.h t_time.c t_timetable.h t_timetable.c table.h table.c main.c